sudo: true
dist: trusty
cache: false
language: python
install:
- export URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-v6.12.0-8b887b22cc-linux-x64.tar.xz
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_65674265f95b_key -iv $encrypted_65674265f95b_iv -in assets/server.key.enc -out assets/server.key -d || true'
- wget -q $URL
- tar -xvJf sfdx-cli-v6.12.0-8b887b22cc-linux-x64.tar.xz
- cd sfdx
- ./install
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- mv force-app/main/test/* force-app/main/default/classes

script:
- "./install/test-in-scratch-org.sh"
after_success:
- sfdx force:org:delete -u ciorg -p
after_failure:
- sfdx force:org:delete -u ciorg -p

